# Generated by Django 4.0.4 on 2022-09-12 12:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=11, verbose_name='Телефон')),
                ('author', models.CharField(max_length=250, verbose_name='Телефон')),
            ],
        ),
    ]
