# Generated by Django 4.0.4 on 2022-09-12 12:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiluser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='id задачи')),
                ('due_date', models.CharField(max_length=250, verbose_name='Срок выполнения задачи')),
                ('priority', models.CharField(max_length=250, verbose_name='Приоритет')),
                ('formulation_task', models.TextField(verbose_name='Формулировка задачи')),
                ('counterparty', models.CharField(max_length=250, verbose_name='Контрагент')),
                ('counterparty_inn', models.CharField(max_length=250, verbose_name='ИНН')),
                ('status', models.CharField(max_length=250, verbose_name='Статус')),
                ('date', models.CharField(max_length=250, verbose_name='Дата окончания')),
                ('author', models.CharField(max_length=250, verbose_name='Телефон')),
                ('refUsers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiluser.profiluser')),
            ],
        ),
    ]
