# Generated by Django 4.0.4 on 2022-09-12 12:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiluser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='id Профиля')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('holding', models.CharField(max_length=250, verbose_name='Холдинг')),
                ('block', models.CharField(max_length=250, verbose_name='Блок')),
                ('form_clients_work', models.CharField(max_length=250, verbose_name='Форма работы')),
                ('type_payment', models.CharField(max_length=250, verbose_name='Тип оплаты')),
                ('client_address', models.CharField(max_length=250, verbose_name='Адрес клиента')),
                ('email_address', models.TextField(verbose_name='Email aдрес')),
                ('counterparty_inn', models.CharField(max_length=250, verbose_name='ИНН')),
                ('cost_hour', models.CharField(max_length=250, verbose_name='Цена за час')),
            ],
        ),
    ]
