# Generated by Django 4.0.4 on 2022-09-12 12:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сomment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('commentContent', models.CharField(max_length=10000, verbose_name='Текст комментария')),
                ('dateTime', models.CharField(max_length=250, verbose_name='Дата')),
                ('author', models.CharField(max_length=250, verbose_name='Автор')),
                ('numberLine', models.CharField(max_length=250, verbose_name='Номер комментария')),
                ('refTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
    ]
